### ISSUE TITLE
It misses the first 10 in my list

### ISSUE THREAD

**Issue by fascenda** [floriandiud/facebook-group-members-scraper#7]
Great tool and it worked but we have 94 members and it ends up with [Download 85 members].

It seems to miss the first 10 (I know 94 less 85 is 9 but it seems to miss the first 10).

**Comment by fascenda** [comment]
I moved the Developer Tools panel Dock-Side to the BOTTOM (horizontal) as you showed in your picture.  That made the difference.

When it was on the RIGHT (vertical) it didn't catch the first 9 or 10.

**Comment by fascenda** [comment]
I'm back to missing the first 10 or 11 no matter where I put the Dock

**Comment by floriandiud** [comment]
Hello. You need to copy/paste the script before clicking on the "Member/People" tab.

**Comment by fascenda** [comment]
Okay thanks I thought I had been doing that, but it did work just now, so I will try to remember don't look at Members page before putting the script in.  Working for me thanks.
